sudo: required
dist: trusty

env:
  global:
    - secure: "McK1+QR6/I/WQD+yL41CBa4B7bdP8evg/dpVFtl1wfkFtVumpYypFuj5cuMS5wKx1lqmN7gN0FmuATYDShqtbIG/JzcO2tnK29OLIiNpuuFRM4ziVQ8LrxeGEDfWf56ShTpk3xFXa8aTfCdvZAOh3FPYfLL63fflZX1iy3aZ2MuKVJDQhfOCtsnAQ+Ga30ZgJ5MZVS2LcY46F/theBFTxbXFLs0t/Co8nNoNsZ7kk7TWFQyAYTIR9ryu9+fZmfwT4s5OufsBHGMzWft0Jv4FjyjlDVZ2ONFNI0JYZaK+m+WdJaZ8GE/R7Oy/I02AYDWF/YV0vis9YXERUT2Yg1uWGP92tnVzTAWb6KMJMXP8SX8satWov97aWuRRNZ9ooEkajtd0PAWJTPKkNQUzzvx2Wpn2ckVMPQO0lqsZNstc+9GAftAS1n6bTnwXwm1Gc7FiTxFRcI4bV1xgvZw45WPxYennnlZYdKQTvLSF3qkSkHF7BouC5qJQGy2Hn8lYOUPqbYP6DDKYehUiuY8KPdK/9kV0y1tiBDfUX64Pxv/AsorAoLefISgk+xQf1Mk67LtLghGU3DwMLVUa2HluxJaGOebPMabqdIE2V7g6VoYtb7i8+kb6bCAGIrqoO4aegu5tSCNsVFvwKBFQBz/9/5RNAhLmn1/gG3fk1YyICJe6Rgc="
    - AWS_ACCESS_KEY_ID=XZQSNWFHKYPQDESUJSTT
    - AWS_HOST=nyc3.digitaloceanspaces.com
    - AWS_BUCKET=com-erianna-travis
    - AWS_HOST_BUCKET="$AWS_BUCKET-$AWS_HOST"
  jobs:
    - BUILD_IMAGE=bionic BUILD_OS=Ubuntu BUILD_OS_VERSION=18.04
    - BUILD_IMAGE=xenial BUILD_OS=Ubuntu BUILD_OS_VERSION=16.04
    - BUILD_IMAGE=trusty BUILD_OS=Ubuntu BUILD_OS_VERSION=14.04
    - BUILD_IMAGE=centos7 BUILD_OS=CentOS BUILD_OS_VERSION=7
    - BUILD_IMAGE=rhel7 BUILD_OS=RHEL BUILD_OS_VERSION=7
    - BUILD_IMAGE=alpine3.7 BUILD_OS=Alpine BUILD_OS_VERSION=3.7
    - BUILD_IMAGE=alpine3.8 BUILD_OS=Alpine BUILD_OS_VERSION=3.8
    - BUILD_IMAGE=alpine3.9 BUILD_OS=Alpine BUILD_OS_VERSION=3.9
    - BUILD_IMAGE=alpine3.10 BUILD_OS=Alpine BUILD_OS_VERSION=3.10

language: generic
services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - if [ "$BUILD_OS" == "Ubuntu" ]; then mkdir -p build/deb/$BUILD_IMAGE; fi
  - if [ "$BUILD_OS" == "Alpine" ]; then mkdir -p build/alpine/v$BUILD_OS_VERSION/x86_64; fi
  - if [ "$BUILD_OS" == "CentOS" ] || [ "$BUILD_OS" == "RHEL" ]; then mkdir -p build/rpm/$BUILD_OS/$BUILD_OS_VERSION/x86_64; fi

script:
  - if [ -n "$TRAVIS_TAG" ]; then export VERSION=$( cut -d '-' -f 1 <<< "$TRAVIS_TAG" ) export RELEASEVER=$( cut -d '-' -f 2 <<< "$TRAVIS_TAG" ); echo "Setting versions via TravisCI Tag"; fi
  - docker-compose run $BUILD_IMAGE
  - if [ "$BUILD_OS" == "Ubuntu" ]; then mv *$BUILD_IMAGE*.deb build/deb/$BUILD_IMAGE; fi
  - if [ "$BUILD_OS" == "Alpine" ]; then mv *.apk build/alpine/v$BUILD_OS_VERSION/x86_64; fi
  - if [ "$BUILD_OS" == "CentOS" ] || [ "$BUILD_OS" == "RHEL" ]; then mv *.rpm build/rpm/$BUILD_OS/$BUILD_OS_VERSION/x86_64; fi
  - find build -type f

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  local-dir: build
  skip_cleanup: true
  detect_encoding: true
  endpoint: https://$AWS_HOST
  on:
    tags: true
    all_branches: false
    repo: charlesportwoodii/libbrotli-build